export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCESS='ORDER_CREATE_SUCESS'
export const ORDER_CREATE_FAILS='ORDER_CREATE_FAILS'

export const ORDER_GET_REQUEST='ORDER_GET_REQUEST'
export const ORDER_GET_SUCESS='ORDER_GET_SUCESS'
export const ORDER_GET_FAILS='ORDER_GET_FAILS'

export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCESS='ORDER_PAY_SUCESS'
export const ORDER_PAY_FAILS='ORDER_PAY_FAILS'
export const ORDER_PAY_RESET='ORDER_PAY_RESET'

export const ORDER_OFUSER_REQUEST='ORDER_OFUSER_REQUEST'
export const ORDER_OFUSER_SUCESS='ORDER_OFUSER_SUCESS'
export const ORDER_OFUSER_FAILS='ORDER_OFUSER_FAILS'
export const ORDER_OFUSER_RESET='ORDER_OFUSER_RESET'

export const ORDERS_ADMIN_REQUEST='ORDERS_ADMIN_REQUEST'
export const ORDERS_ADMIN_SUCCESS='ORDERS_ADMIN_SUCCESS'
export const ORDERS_ADMIN_FAILS='ORDERS_ADMIN_FAILS'
export const ORDERS_ADMIN_RESET='ORDERS_ADMIN_RESET'

export const ORDER_DELIVERED_REQUEST='ORDER_DELIVERED_REQUEST'
export const ORDER_DELIVERED_SUCESS='ORDER_DELIVERED_SUCESS'
export const ORDER_DELIVERED_FAILS='ORDER_DELIVERED_FAILS'
export const ORDER_DELIVERED_RESET='ORDER_DELIVERED_RESET'
