export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCESS='ORDER_CREATE_SUCESS'
export const ORDER_CREATE_FAILS='ORDER_CREATE_FAILS'

export const ORDER_GET_REQUEST='ORDER_GET_REQUEST'
export const ORDER_GET_SUCESS='ORDER_GET_SUCESS'
export const ORDER_GET_FAILS='ORDER_GET_FAILS'

export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCESS='ORDER_PAY_SUCESS'
export const ORDER_PAY_FAILS='ORDER_PAY_FAILS'
export const ORDER_PAY_RESET='ORDER_PAY_RESET'
