export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_SUCESS ='PRODUCT_SUCESS'
export const PRODUCTS_FAILS ='PRODUCTS_FAILS'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCESS ='PRODUCT_DETAIL_SUCESS'
export const PRODUCTS_DETAIL_FAILS ='PRODUCTS_DETAIL_FAILS'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCESS ='PRODUCT_DELETE_SUCESS'
export const PRODUCTS_DELETE_FAILS ='PRODUCTS_DELETE_FAILS'


export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCESS ='PRODUCT_CREATE_SUCESS'
export const PRODUCTS_CREATE_FAILS ='PRODUCTS_CREATE_FAILS'
export const PRODUCTS_CREATE_RESET='PRODUCTS_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCESS ='PRODUCT_UPDATE_SUCESS'
export const PRODUCTS_UPDATE_FAILS ='PRODUCTS_UPDATE_FAILS'
export const PRODUCTS_UPDATE_RESET='PRODUCTS_UPDATE_RESET'