export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_SUCESS ='PRODUCT_SUCESS'
export const PRODUCTS_FAILS ='PRODUCTS_FAILS'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCESS ='PRODUCT_DETAIL_SUCESS'
export const PRODUCTS_DETAIL_FAILS ='PRODUCTS_DETAIL_FAILS'