export const USER_LOGIN_REQUEST= 'USER_LOGIN_REQUEST'
export const USER_LOGIN_FAILS= 'USER_LOGIN_FAIL'
export const USER_LOGIN_SUCESS= 'USER_LOGIN_SUCESS'
export const USER_LOGOUT= 'USER_LOGOUT'

export const USER_REGISTER_REQUEST= 'USER_REGISTER_REQUEST'
export const USER_REGISTER_FAILS= 'USER_REGISTER_FAIL'
export const USER_REGISTER_SUCESS= 'USER_REGISTER_SUCESS'

export const USER_DATA_REQUEST= 'USER_DATA_REQUEST'
export const USER_DATA_FAILS= 'USER_DATA_FAIL'
export const USER_DATA_SUCESS= 'USER_DATA_SUCESS'
export const USER_DATA_RESET= 'USER_DATA_RESET'



export const USER_UPDATE_REQUEST= 'USER_UPDATE_REQUEST'
export const USER_UPDATE_FAILS= 'USER_UPDATE_FAIL'
export const USER_UPDATE_SUCESS= 'USER_UPDATE_SUCESS'
export const USER_UPDATE_RESET= 'USER_UPDATE_RESET'


export const USER_LIST_REQUEST= 'USER_LIST_REQUEST'
export const USER_LIST_FAILS= 'USER_LIST_FAIL'
export const USER_LIST_SUCESS= 'USER_LIST_SUCESS'
export const USER_LIST_RESET= 'USER_LIST_RESET'

export const USER_DELETE_REQUEST= 'USER_DEELTE_REQUEST'
export const USER_DELETE_FAILS= 'USER_DELETE_FAIL'
export const USER_DELETE_SUCESS= 'USER_DELETE_SUCESS'


export const USER_UPDATES_REQUEST= 'USER_UPDATE_REQUEST'
export const USER_UPDATES_FAILS= 'USER_UPDATE_FAIL'
export const USER_UPDATES_SUCESS= 'USER_UPDATE_SUCESS'
export const USER_UPDATES_RESET= 'USER_UPDATE_RESET'
